kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2025-09-24T09:52:37Z"
  labels:
    app.kubernetes.io/instance: nginx
    run: nginx-service
  name: nginx-service
  namespace: test-argocd
  resourceVersion: "2791663"
  uid: 31373f68-62c9-491e-b887-1db73a76d9c0
spec:
  host: nginx-service-test-argocd.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2025-09-24T09:52:37Z"
      status: "True"
      type: Admitted
    host: nginx-service-test-argocd.apps-crc.testing
    routerCanonicalHostname: router-default.apps-crc.testing
    routerName: default
    wildcardPolicy: None
