apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2025-09-24T09:14:33Z'
  labels:
    app.kubernetes.io/instance: nginx
    run: nginx-service
  managedFields:
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:run: {}
        f:spec:
          f:port:
            .: {}
            f:targetPort: {}
          f:to:
            f:kind: {}
            f:name: {}
            f:weight: {}
          f:wildcardPolicy: {}
      manager: oc
      operation: Update
      time: '2025-09-24T09:14:33Z'
    - apiVersion: route.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:ingress: {}
      manager: openshift-router
      operation: Update
      subresource: status
      time: '2025-09-24T09:14:33Z'
  name: nginx-service
  namespace: test-argocd
  resourceVersion: '2783066'
  uid: cef35781-b02f-41d5-8c0c-1f2fa0f4a47b
spec:
  host: nginx-service-test-argocd.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2025-09-24T09:14:33Z'
          status: 'True'
          type: Admitted
      host: nginx-service-test-argocd.apps-crc.testing
      routerCanonicalHostname: router-default.apps-crc.testing
      routerName: default
      wildcardPolicy: None
